"use server"

import { createClient } from "../supabase/server"

// if this returns null the function using this should know that something went wrong
export async function createTag(tag: string) {
    const supabase = await createClient();

    // insert the tag only if it doesn't already exist
    // check if it exists
    const { data: tagExists } = await supabase
        .from("tags")
        .select()
        .eq("tag", tag)
        .single();

    // if the tag doesn't exist then add it to the db
    if (!tagExists) {

        // insert the data and return it so we can get the autogenerated id
        const { data: tagData, error } = await supabase.from("tags").insert({ tag: tag }).select().single();

        if (error) {
            console.error("Error putting a tag into the database", error);
            return null;
        }

        return tagData?.id;
    } else {
        // return the id if it already exists
        return tagExists?.id;
    }
} 
